config/routes.rb
Demo::Application.routes.draw do
  resources :mircoposts

  resources :users

end

app/models/mircopost.rb
class Mircopost < ActiveRecord::Base
  belongs_to :user

  validates :content, :length => { :maximum => 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :mircoposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mircoposts_controller.rb
class MircopostsController < ApplicationController
  # GET /mircoposts
  # GET /mircoposts.xml
  def index
    @mircoposts = Mircopost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mircoposts }
    end
  end

  # GET /mircoposts/1
  # GET /mircoposts/1.xml
  def show
    @mircopost = Mircopost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mircopost }
    end
  end

  # GET /mircoposts/new
  # GET /mircoposts/new.xml
  def new
    @mircopost = Mircopost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mircopost }
    end
  end

  # GET /mircoposts/1/edit
  def edit
    @mircopost = Mircopost.find(params[:id])
  end

  # POST /mircoposts
  # POST /mircoposts.xml
  def create
    @mircopost = Mircopost.new(params[:mircopost])

    respond_to do |format|
      if @mircopost.save
        format.html { redirect_to(@mircopost, :notice => 'Mircopost was successfully created.') }
        format.xml  { render :xml => @mircopost, :status => :created, :location => @mircopost }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mircopost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mircoposts/1
  # PUT /mircoposts/1.xml
  def update
    @mircopost = Mircopost.find(params[:id])

    respond_to do |format|
      if @mircopost.update_attributes(params[:mircopost])
        format.html { redirect_to(@mircopost, :notice => 'Mircopost was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mircopost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mircoposts/1
  # DELETE /mircoposts/1.xml
  def destroy
    @mircopost = Mircopost.find(params[:id])
    @mircopost.destroy

    respond_to do |format|
      format.html { redirect_to(mircoposts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mircoposts_helper.rb
module MircopostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mircoposts/_form.html.erb
<%= form_for(@mircopost) do |f| %>
  <% if @mircopost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mircopost.errors.count, "error") %> prohibited this mircopost from being saved:</h2>

      <ul>
      <% @mircopost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mircoposts/edit.html.erb
<h1>Editing mircopost</h1>

<%= render 'form' %>

<%= link_to 'Show', @mircopost %> |
<%= link_to 'Back', mircoposts_path %>

app/views/mircoposts/index.html.erb
<h1>Listing mircoposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mircoposts.each do |mircopost| %>
  <tr>
    <td><%= mircopost.content %></td>
    <td><%= mircopost.user_id %></td>
    <td><%= link_to 'Show', mircopost %></td>
    <td><%= link_to 'Edit', edit_mircopost_path(mircopost) %></td>
    <td><%= link_to 'Destroy', mircopost, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mircopost', new_mircopost_path %>

app/views/mircoposts/new.html.erb
<h1>New mircopost</h1>

<%= render 'form' %>

<%= link_to 'Back', mircoposts_path %>

app/views/mircoposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @mircopost.content %>
</p>

<p>
  <b>User:</b>
  <%= @mircopost.user_id %>
</p>


<%= link_to 'Edit', edit_mircopost_path(@mircopost) %> |
<%= link_to 'Back', mircoposts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>